version: "3.0"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: YES
      NEO4J_AUTH: neo4j/your_password
    restart: always
    volumes:
      # - ./neo4j.conf:/conf/neo4j.conf # This is the main configuration file.
      - neo4j_data:/data
      - neo4j_data:/logs

volumes:
  neo4j_data:
